name: WISC

channels:
    - conda-forge

dependencies:
        - python=3.6
        - gdal
        - numpy
        - pandas
        - shapely
        - geopandas
        - pathos
        - rasterio
        - matplotlib
        - basemap
        - SALib
        - urllib3
        - scikit-learn
        - xlrd
        - tqdm
    - pip:
        - rasterstats
