name: WISC

dependencies:
        - python=3.6
        - gdal
        - numpy
        - pandas
        - shapely
        - geopandas
        - pathos
        - rasterio
        - rasterstats
        - matplotlib
        - basemap
        - SALib
        - urllib3
        - scikit-learn
        - xlrd
